### ISSUE TITLE
"server-settings.json" can become invalid because previous data is not replaced

### ISSUE THREAD

**Issue by pv11** [exceptionless/Exceptionless.Net#267] opened 2022-01-16 15:08 UTC
Steps to reproduce:

1. have at least one custom setting. Example:
![bug-1](https://user-images.githubusercontent.com/679381/149665611-c187a6b8-3fc4-4ea1-a27c-d70b930242a5.png)

1.1 Let the client update the local "server-settings.json" file

2. change the custom settings in such a way that the now value is shorter than the original value. Example:
![bug-2](https://user-images.githubusercontent.com/679381/149665663-070f6053-a381-4478-bac8-58d8e3c176df.png)

3. After the client updates the local "server-settings.json" file, the JSON will be invalid. Example:
![bug-3](https://user-images.githubusercontent.com/679381/149665691-62aa020a-46ac-414f-81d0-10e8eba14169.png)

Tested using "Exceptionless.dll" 4.6.2 in a C# project with .Net Framework 4.5.2

**Comment by pv11** [comment] 2022-01-17 17:16
The problem is observable like this:

- create a new console program (in this case I'm using .Net framework 4.5.2)
- add the appropriate Exceptionless libray
- write the following code and execute (change the apiKey; change "c:\temp" to other folder if needed ):

```c#
        static void Main(string[] args)
        {
            const string apiKey = "TLFsO5wRvyoMDiF3SSJOgkskCNhTHwtTTN75iWvj";
            const string useFolder = @"c:\temp";

            var serverSettingsFile = Path.Combine(useFolder, apiKey.Substring(0,8), "server-settings.json");

            ExceptionlessClient.Default.Configuration.UseFolderStorage(useFolder);
            ExceptionlessClient.Default.Configuration.UseFileLogger(Path.Combine(useFolder, $"Exceptionless.log"));

            ExceptionlessClient.Default.Startup(apiKey);

            while (true)
            {
                Console.WriteLine("Change Client Configuration Settings and watch the result here (you might need to wait up to 2 minutes...)");

                System.Threading.Thread.Sleep(5000);

                if (File.Exists(serverSettingsFile))
                {
                    Console.WriteLine($"Current settings (at {DateTime.Now:u}):");
                    Console.ForegroundColor = ConsoleColor.Cyan;
                    Console.WriteLine(File.ReadAllText(serverSettingsFile));
                    Console.ResetColor();
                }
            }
        }
```


![console result](https://user-images.githubusercontent.com/679381/149812794-e1ef9545-cd09-4660-b576-916667acdccb.png)

**Comment by niemyjski** [comment] 2022-01-18 15:10
Does this happen if you don't use a temp folder? I just tried it and I couldn't reproduce

![image](https://user-images.githubusercontent.com/1020579/149963624-42166705-e58f-4fd6-8f61-c248c61c417a.png)

**Comment by pv11** [comment] 2022-01-18 18:05
Apparently the problem occurs only when using a custom folder to settings storage, i. e.:
`ExceptionlessClient.Default.Configuration.UseFolderStorage("c:\\myfolder");`

It looks OK when using:
`ExceptionlessClient.Default.Configuration.UseIsolatedStorage();`

(one can confirm by opening the file `"C:\ProgramData\IsolatedStorage\xxx\AssemFiles\TLFsO5wR\server-settings.json"` )

**Comment by niemyjski** [comment] 2022-01-18 18:36
What operating system are you using? I'm on Windows 11 and I also tried it with `UseFolderStorage("store")` and it worked

**Comment by pv11** [comment] 2022-01-20 11:10
I'm using Windows 10 Pro.

However, I downloaded the entire code from this repository and tested by referencing directly the VIsual Studio project into my test console (instead in referencing the complied assemblies), and that way it worked OK.

So the mistery remains.

**Comment by niemyjski** [comment] 2022-01-25 14:55
I've been able to reproduce using the nuget package and not source. I'll try and track this down

**Comment by niemyjski** [comment] 2022-01-26 13:28
I need to get better about pushing more frequent releases. I just noticed after tracking this down that this was actually fixed in this pr quite some time ago: https://github.com/exceptionless/Exceptionless.Net/pull/247 I'm pushing a new release in a few minutes.

**Closed by niemyjski** 2022-01-26 13:28 UTC
Labels: investigating

**Comment by niemyjski** [comment] 2022-01-26 13:42
https://github.com/exceptionless/Exceptionless.Net/releases/tag/v4.7.0
