### ISSUE TITLE
ToExceptionless breaks when the exception isn't loadable. FileNotFoundException is thrown. 

### ISSUE THREAD

**Issue by danlarson** [exceptionless/Exceptionless.Net#14] opened 2015-04-20 23:10 UTC
ToExceptionless should never (ever) fail, because we use it in error handling code. :) 

When the exception is thrown in another app domain and caught in the appdomain that doesn’t have the exception defined, when we call ToExceptionless is throws a FileNotFound exception. 
Can you add error handling in ToExceptionless so if it fails with this, it gives the best report it can but doesn’t fail? 

Here is my hack at error handling with a custom extension method that calls ToExceptionless: 

        public static EventBuilder ToExceptionModel(this Exception exception, ContextData pluginContextData = null, 
            ExceptionlessClient client = null)
        {
            try
            {
                try
                {
                    return exception.ToExceptionless();
                }
                catch (FileNotFoundException)
                {
                    if (client == null)
                    {
                        client = ExceptionlessClient.Default;
                    }
                    if (pluginContextData == null)
                    {
                        pluginContextData = new ContextData();
                    }

                    pluginContextData.SetException(new ApplicationException(exception.Message));
                    var builder = client.CreateEvent(pluginContextData);
                    builder.AddObject(exception.StackTrace, name: "StackTrace");
                    return builder;
                }
                catch
                {
                    return new ApplicationException("Could not create exception model. Original exception: "
                        + exception.Message).ToExceptionless();
                }
            }
            catch {
                return new ApplicationException(
                    "An unknown error occurred and we could not create the exception model.").ToExceptionless();
            }
        }

Here’s an example stack trace from our app that causes this: 

System.IO.FileNotFoundException: Could not load file or assembly 'Demo.Service, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName fileName, System.String codeBase, System.Security.Policy.Evidence assemblySecurity, System.Reflection.RuntimeAssembly locationHint, System.Threading.StackCrawlMark& stackMark, System.IntPtr pPrivHostBinder, System.Boolean throwOnFileNotFound, System.Boolean forIntrospection, System.Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity, System.Reflection.RuntimeAssembly reqAssembly, System.Threading.StackCrawlMark& stackMark, System.IntPtr pPrivHostBinder, System.Boolean throwOnFileNotFound, System.Boolean forIntrospection, System.Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoad(System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Threading.StackCrawlMark& stackMark, System.IntPtr pPrivHostBinder, System.Boolean forIntrospection)
at System.Reflection.RuntimeAssembly.InternalLoad(System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Threading.StackCrawlMark& stackMark, System.Boolean forIntrospection)
at System.Reflection.Assembly.Load(System.String assemblyString)
at System.Runtime.Serialization.FormatterServices.LoadAssemblyFromString(System.String assemblyName)
at System.Reflection.MemberInfoSerializationHolder..ctor(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
at System.Exception.GetExceptionMethodFromString
at System.Exception.GetTargetSiteInternal
at Exceptionless.Extensions.ToErrorModelExtensions.ToErrorModel(System.Exception exception, Exceptionless.Logging.IExceptionlessLog log)
at Exceptionless.ExceptionlessClient.ToError(Exceptionless.ExceptionlessClient client, System.Exception exception, System.String submissionMethod, System.Collections.Generic.IDictionary`2 contextData)
at Exceptionless.ErrorExtensions.ToExceptionless(System.Exception exception, System.Boolean addDefaultInformation, System.Collections.Generic.IDictionary`2 pluginContextData, Exceptionless.ExceptionlessClient client)
at CustomerCodeRemovedHere.cs

**Comment by niemyjski** [comment] 2015-04-21 14:19
It looks like only the target site property is blowing up. Is there any chance you could create a small sample that reproduces this and then we can ensure we do the right fix. I think all we would need to do is do a try catch around the target site logic: https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Extras/Extensions/ToErrorModelExtensions.cs#L54-L57

**Comment by niemyjski** [comment] 2015-06-09 16:17
@danlarson is there any chance you could create a small sample so we can ensure we get the correct fix for this.

**Comment by niemyjski** [comment] 2015-08-24 18:40
@danlarson is there any chance you could create a small sample so we can ensure we get the correct fix for this.

**Closed** 2015-11-23 23:32 UTC
Labels: bug, enhancement, help wanted
