### ISSUE TITLE
Serializer doesn't special case abbreviations.

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#2] opened 2015-03-12 22:48 UTC
When I use the EventBuilder.AddObject method, with an object containing a dictionary<string, int>, I see on Exceptionless (Extended Data) that the key of the dictionary is changed (eg. "MP3" -> "m_p3", "FLAC" -> "F_l_a_c"). I use latest nuget package Exceptionless.Wpf.

Thanks

``` c#
ExceptionlessClient.Default.CreateLog("Source", "Message").AddObject(new LogInfo2()).Submit();
```

``` c#
public class LogInfo2
   {
      public LogInfo2()
      {
         files.Add("MP3", 281);
         files.Add("FLAC", 23);
      }

      private readonly Dictionary<string, int> files = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);

      public Dictionary<string, int> Files
      {
         get { return files; }
      }      
   }
```

**Comment by niemyjski** [comment] 2015-03-13 23:44
I'll take a look into this. It appears to be a bug in the ToLowerUnderscoredWords method:  

https://github.com/exceptionless/Exceptionless.Net/blob/fbdf657c968e8f5e819b1593304649e0ce8f2725/Source/Shared/Extensions/StringExtensions.cs#L18-L33

Is there any chance you could submit a unit test and patch for this?

**Comment by CyberSinh** [comment] 2015-03-13 23:59
Before trying to fix it, can you explain me what that method is supposed to do and in what context do you use it?

Thanks.

**Comment by niemyjski** [comment] 2015-03-14 13:54
It's supposed to break on Uppercase and and convert a worded string into lower case with a separator of _.

*Examples:*
```
BlakeNiemyjski -> blake_niemyjski
Blake   Niemyjski -> blake_niemyjski
Blake_ niemyjski -> blake_niemyjski
```

The issue is that it's not taking into account abbreviations like MP3 or IP Address.
```
MP3 -> mp3
IP Address -> ip_address
```

**Comment by CyberSinh** [comment] 2015-03-14 22:21
I fix this bug and sent you pull request (with fix and unit tests).

**Comment by niemyjski** [comment] 2015-03-16 18:58
Awesome, my only concern is that although the regex route is clean, it has a very good chance of being really slow compared to a for loop. This code will run to serialize every property of every event and needs to be lightning quick. Could you update the serializer tests to check the before and after implementation after 10k iterations of a complex event to see the impact?

**Comment by niemyjski** [comment] 2015-03-16 18:59
If there is an impact we'd need to convert this to a for loop, which might be better in the long run (thoughts?)

**Comment by CyberSinh** [comment] 2015-03-16 20:32
I made some benchmark (on my old laptop) : 
http://pastebin.com/XUxT8qAm

For 10k iterations:
- old buggy code (with for loop) : 10 ms
- new regex code : 140 ms
- new regex code (with RegexOptions.Compiled) : 80 ms

So, the new regex code, with RegexOptions.Compiled seems to be the best way. 
80 ms for 10k iteractions should be imperceptible for user in typical use.

**Comment by CyberSinh** [comment] 2015-03-16 23:00
I realized that RegexOptions.Compiled is not an option available for portable assembly. However, 140 ms for 10k iterations should be fine.

What do you think?

**Comment by niemyjski** [comment] 2015-03-16 23:06
I don't think regexes will work to be honest.  This code needs to run server side and client side and be very performant. It will be deserializing and serializing everything. 70ms adds up quick esp when you have millions of events

Sent from Outlook




On Mon, Mar 16, 2015 at 4:00 PM -0700, "CyberSinh" <notifications@github.com> wrote:












I realized that RegexOptions.Compiled is not an option available for portable assembly. However, 140 ms for 10k iterations should be fine.



What do you think?

**Comment by CyberSinh** [comment] 2015-03-16 23:40
I didn't know the algo should be used in server side too. My fix targets only the client library (without millions of events to process).

**Comment by niemyjski** [comment] 2015-03-17 14:31
Yeah, I'm just thinking you may be logging all trace messages and on a busy app (client side client) could see thousands of events a minute, so every little bit helps as it's less work the client has to do and more for your app.

**Comment by niemyjski** [comment] 2015-03-17 14:32
I think we may have had code that detects abbrs in the 1.x codebase but we'd have to look. Basically, I'd just check (current char is upper case and the previous character is uppercase then don't prepend a _

**Comment by CyberSinh** [comment] 2015-03-17 22:14
Hi Blake,

I am not easily discouraged. ;-)

I replaced the regex code by a for loop implementation in my last commit. 
The 10k iterations only takes 15 ms now. 

So, performance is much better but the code is less elegant... Hope you will find the code useful.

**Comment by niemyjski** [comment] 2015-03-17 22:30
Awesome! Thank you, it mwans a lot. I've left some comments on the commit. Also, have you had a chance to sign our cla (https://www.clahub.com/agreements/exceptionless/Exceptionless)?

**Comment by CyberSinh** [comment] 2015-03-18 08:54
CLA signed and comments responded.

**Comment by niemyjski** [comment] 2015-03-18 16:22
Thanks, I'll try and accept this pull request soon(by the end of the week). I need to pull this down and do some testing server side to ensure nothing else is affected.

**Comment by CyberSinh** [comment] 2015-03-30 21:29
Hi Blake,
The PR has not been merged yet. Do you have any issue with the code?

**Comment by niemyjski** [comment] 2015-03-30 21:56
Hello, yes I found some issues and commented on them here: https://github.com/exceptionless/Exceptionless.Net/pull/3 I should have commented on the issues here (my bad)

**Comment by niemyjski** [comment] 2015-04-27 01:19
I've added this to our road map of something we will fix soon! https://github.com/exceptionless/Exceptionless/blob/master/README.md

**Comment by niemyjski** [comment] 2015-04-27 01:19
I feel really bad that we haven't accepted this yet, but we will get it tested and integrated soon.

**Comment by niemyjski** [comment] 2015-05-06 19:02
This is also effecting request info (Extended data)..

**Comment by niemyjski** [comment] 2015-06-09 18:20
@CyberSinh Just and update. I'm working on this as well as working on getting rid of mongo. What this means is we are moving to only elastic search for storage which means one serialization setting that needs to be tested. These will go hand in hand and will be tested. So the news is this will be merged really soon.

**Comment by niemyjski** [comment] 2015-06-24 14:19
@CyberSinh I just spent a few hours going over your change and we really like it and really really want it... We tried to implement it into our big server changes that are in coming. However, we may have to punt on this for a while. Here are the issues we are seeing after discussion and testing.

* We have millions of events stored and indexed in elastic search.
  * This change would cause anyone who has extended data indexed to have to do two searches to get at the same data (mp3 and m_p_3) as it's an unknown field so we wouldn't know how to handle it during reindexing.
  * We'd have to write a reindex script and run it to rename our fields like i_p_address so our models will deserialize, but the issue is, you can't use neither the old or new serializer while it's running (we'd have to figure this out further).
* We'll have to update all clients both JavaScript and .NET with the code changes (not a problem).
* We'll have to write a event migration script to rename json fields when we parse the event for all legacy events (easy to do just another thing to add to the task list).

**Comment by niemyjski** [comment] 2015-06-24 14:20
We need to address these bullet points before this can happen :(.

**Comment by niemyjski** [comment] 2016-09-23 21:22
We are in the process of upgrading the cluster and reindexing all data. We are going to use the new snake_case formatter built into json.net 9.0.1

**Closed** 2022-05-27 09:45 UTC
Labels: bug, help wanted, 0 - Backlog, Hacktoberfest
