### ISSUE TITLE
Queue data is not persisted

### ISSUE THREAD

**Issue by airwareic** [exceptionless/Exceptionless.Net#53] opened 2015-08-29 09:20 UTC
After 3 unsuccessful attempts to upload event data or 1 day in the queue, event data is lost. This data is vital for my team, where the application is used 80% offline.

**Comment by niemyjski** [comment] 2015-08-29 21:53
Hello,

Can you please attach the troubleshooting logs. Where you able to step through this and see why it isn't being persisted? Are you seeing an exception being thrown?

**Comment by airwareic** [comment] 2015-08-29 22:09
I don't have logs to show what's causing me so much headache because this
is intended behavior. All that gets dumped to the logs on my end are
messages about process suspension. I found this issue by cloning the .NET
client repo and stepping through until I saw what was being done around
locks and attempts.

I'm not in front of my work machine and don't have my laptop so I can't get
the exact details, but there's a call to clean the queue before processing
that intentionally deletes event files that have attempted upload 3 times
or are older than one day- this is hard coded.

Can you open this up for a PR? I've written a PR to fix this in a way that
is accessible in the exceptionless config section by setting persistQueue
to true.

**Comment by airwareic** [comment] 2015-08-29 22:26
I think one of the points of confusion here is that while suspend
processing is called when offline, that isn't persisted when I next restart
the application, so if my application crashes offline and then I restart
it, the queue can be cleaned unintentionally.

**Comment by airwareic** [comment] 2015-08-30 03:41
Hey Blake, I'm having auth issues and can't chat through the site. The best
time for me to really get to any of this is Monday. So let's pick up there.
I can remote and add more github details there.

**Comment by niemyjski** [comment] 2015-08-30 03:53
Sounds good, you just need to fork the repo and then you can create a pull request. What authentication issues are you seeing? Let's talk more on Monday.

**Comment by airwareic** [comment] 2015-08-30 03:55
Oh, that's not on your end, sorry. Duo 2FA isn't working through my company
gmail account. It's a duo setup issue.

**Comment by niemyjski** [comment] 2015-08-31 15:44
No problem, please let me know when you are able to enter a meeting. I'm going to be traveling this afternoon.

**Comment by airwareic** [comment] 2015-08-31 15:45
How about 10:15?

**Comment by airwareic** [comment] 2015-08-31 22:12
Hey Blake,

My team is waiting on my PR in exceptionless.net as part of a hotfix to our
product. I know you're traveling right now, but is there anyone else who
can take point and provide me with an initial review?

Thanks,
Eric

**Comment by niemyjski** [comment] 2015-09-01 15:45
I've asked a teammate to review it as well so were on the same page. I'm trying to be as open minded and grateful for this pr as possible. My initial feedback is I don't see us accepting this pull request in the current form. I think the changes for readability actually makes it less readable as the previous code was short and concise. Also the status code changes breaks some scenarios (pcl), as I've had to revert that exact code you had a few months ago. 

I think there could be an issue here and I'd like exact steps on how to reproduce it locally, I'd even be more than happy to enter a remote meeting with you and take a look at it. I think we should address the core issue is that it's being deleted when it shouldn't be. 

Too be honest, I'm still not 100% sure introducing this functionality is a good idea as it could be misused in a few ways.
1. The queue data could really grow to a point where you run out of disk space.
2. The old queue data could be submitted outside of your retention period thus causing more work just to be discarded server side and counting against plan limits.

@ejsmith could you please leave your feedback here as well.

**Comment by niemyjski** [comment] 2015-09-01 15:48
It's worth noting that we have to support and have a commercial application that supports offline as well. Offline support is a very important to Exceptionless.

**Comment by airwareic** [comment] 2015-09-01 16:05
I see where you're coming from on these points, and considered them as I
was making this change. It'd be helpful for me to discuss some of these
with you in a call.

When it comes to offline mode, the critical part is never losing data.
Beyond arbitrary policies about queue size it seems impossible to cap that.
Especially because each price point has a different retention limit- the
best policy could be to fetch that from your server, I suppose.
Additionally, age checking is something that should be done server side,
right? It just doesn't seem right gor the client to perform that check
unless it already knows the true retention policy.

When do you think you're able to remote today?

**Comment by niemyjski** [comment] 2015-09-01 16:08
I'm free anytime today (minus lunch). I'm on gitter if you want to chat there.

**Comment by ejsmith** [comment] 2015-09-01 16:18
What if we just had options that allowed you to change how long and how many retries it took before an item was discarded?

**Comment by ejsmith** [comment] 2015-09-01 16:21
Here are some insights into why we made it work this way. In the past we ran into issues where people's servers crashed because the queue filled up their disk.

**Comment by airwareic** [comment] 2015-09-01 16:24
Right, that would be great, but I wanted to talk to you guys about how you
saw that being presented. Should we make a queue settings section? Should
the time be in days or in timespan? If we make this configurable, is there
server side age validation? Both should be nullable because teams like mine
most likely just don't care and would like a freer mode.

Let's discuss this later today, I like the idea.

**Comment by niemyjski** [comment] 2015-09-01 19:18
Fixed in: https://github.com/exceptionless/Exceptionless.Net/pull/55

**Closed** 2015-09-01 20:19 UTC
