### ISSUE TITLE
Not every exceptions are caught in MVC or WebAPI

### ISSUE THREAD

**Issue by skoub** [exceptionless/Exceptionless.Net#70] opened 2016-01-22 20:39 UTC
Some exceptions in my MVC application are not caught by Exceptionless and don't know why:

- When a mvc controller cannot be created

*InvalidOperationException: An error occurred when trying to create a controller of type 'WebApplication2.Controllers.HomeController'. Make sure that the controller has a parameterless public constructor.*

- If the error is outside MVC, the error is not caught. For example, if a class is being created from Autofac and his constructor throw an exception, Exceptionless will not caught the error. If a create the same object from an ActionResult and the constructor throw the error, it WILL be caught.

- If i have a bad link (404 not found), i have nothing in the Exception dashboard nor broken links dashboard.

- in WebAPI, if an api call my repository and my repository throw an exception, it is not caught. This is strange because if i call the same method from MVC, the error IS caught.

Any idea why some exceptions are logged and others don't?

**Comment by niemyjski** [comment] 2016-01-22 22:27
@skoub we recently disconnected the global mvc error handler as we were getting duplicate exceptions, upon review it looked like we wouldn't need to wire up to it anymore. Can you try wiring back up to this and see if this fixes this behavior.

https://github.com/exceptionless/Exceptionless.Net/commit/6943b0cf57b7dad07b0f421a042974815180c3f0

For Web API 2.1 can you create a new exception filter with the following content and see if this resolves your web api errors: https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Platforms/WebApi/ExceptionlessExceptionLogger.cs

If you could update our sample applications with reproduction steps. I'd be more than happy to take a close look under the debugger and get these fixed.

**Comment by skoub** [comment] 2016-01-23 02:35
I will give it a try next week and give you news. Thank you for your help!

**Comment by niemyjski** [comment] 2016-01-28 20:36
@skoub were you able to verify if these changes worked?

**Comment by skoub** [comment] 2016-01-28 20:45
I haven't had time to play with it. But if you had duplicate error with the global mvc error handler, it will come back if it plug it back for sure. So we will have to search why we have duplication.

**Comment by skoub** [comment] 2016-02-01 02:44
i have tested the mvc fix and it seems to solve the problem. I haven't tested the Api fix yet.

**Comment by skoub** [comment] 2016-02-01 02:48
Look at the screenshot, is it possible that this is the problem of the duplicate inserts that you have?

![image](https://cloud.githubusercontent.com/assets/865002/12707602/3d5d9fac-c864-11e5-9978-957997d31fcb.png)

**Comment by niemyjski** [comment] 2016-02-01 13:15
Yeah looks like it I also see the debugger display is pouting to a property that doesn't exist either

**Comment by niemyjski** [comment] 2016-02-01 13:15
Those two errors would be the same but the stack trace will change a bit between the handlers

**Comment by niemyjski** [comment] 2016-02-01 13:16
I think I may have an ideal on how to fix that

**Comment by niemyjski** [comment] 2016-02-02 17:20
@ejsmith I saw that a few different services clients store a `@flag` in the exceptions `Data` property. I think we could also do the same and then we just check  for this in the duplicate checker plugin... What are your thoughts.

**Comment by skoub** [comment] 2016-02-02 18:11
I saw the same thing myself. Using a flag to tell that the exception is already grabbed by your client. The logic to remove the duplicate entry will be on the client side or server side?

**Comment by niemyjski** [comment] 2016-02-02 18:17
This would all be on the client.

**Comment by ejsmith** [comment] 2016-02-03 17:31
Sounds good to me.

**Comment by niemyjski** [comment] 2016-02-04 17:12
This should be fixed by this commit: https://github.com/exceptionless/Exceptionless.Net/commit/564d6eb6848ddac0456646d7b8b88fa039561b17

We will deploy this when we release the next client build (hopefully) in the next week. The work around is to call our extension methods as described above until we fix this. Please let me know if you have any questions.

**Closed by niemyjski** 2016-02-04 17:12 UTC
Labels: bug, investigating
