### ISSUE TITLE
Deadlock in DuplicateCheckerPlugin

### ISSUE THREAD

**Issue by lscpike** [exceptionless/Exceptionless.Net#182] opened 2018-03-10 16:08 UTC
The lock in EnqueueMergedEvents is held whilst calling external code (_context.Client.OnSubmittingEvent()).

The deadlock I saw involved the UI thread:
- Exception on UI calling DuplicateCheckerPlugin.Run attempting to lock.
- EnqueueMergedEvents calling _context.Client.OnSubmittingEvent() => ExceptionlessWindowsExtensions.OnSubmittingEvent which opens a dialog.

Sorry I lost the stacks so can't include.

**Comment by niemyjski** [comment] 2018-03-11 14:21
Thank you a million for reporting this issue, we greatly appreciate it. I looked at the call stacks and tried to reproduce the issue by submitting unhandled exceptions on the ui thread (which triggers the submit dialog) and then 5 events in a tight loop to try and trigger the duplicate checker lock. I wasn't able to reproduce but if you can get me a stack trace or let me know if the code I just referenced above needs some tweaking that would be greatly appreciated.

**Comment by lscpike** [comment] 2018-03-11 18:12
It seems we had a windows handle leak that was causing all sorts of issues. In fact that was the exception being reported. The general issue was probably what caused the Form.ShowDialog to block for us. I'm not 100% on that though. It's going to be very hard to reproduce that unfortunately. 

It's best not to raise events (SubmittingEvent) whilst holding locks anyway. You never know what it's going to do and is often the cause of deadlocks!

Feel free to close this particular issue if you want though.

**Comment by ejsmith** [comment] 2018-03-11 18:13
I agree. We should change it up to lock for the shortest possible time even if that means we need to change it to use the lock multiple times.

**Comment by niemyjski** [comment] 2018-03-12 13:06
I did a second code review of this code and I'm not sure how much of the lock can be removed. I did try and convert it to use concurrent queues with no locking and that helped a lot on non PCL platforms but the concurrency tests still failed every third test run.

**Comment by niemyjski** [comment] 2018-03-12 13:10
I think it's safe to remove the locking around the `EnqueueMergedEvents` because it's the only thing ever dequeueing, however looking at it there could be a race condition than where the counts could be  incremented by  the plugin run (lines 44-50). But this would resolve the locking around any dialogs being shown.

**Comment by niemyjski** [comment] 2018-05-09 14:25
@lscpike is there any chance you could attach a sample

**Comment by lscpike** [comment] 2018-08-18 10:47
Sorry for the really slow response. I think I was on holiday and completely forgot about it.

We've just had this issue pop up again. As you hadn't yet fixed it I thought I'd do a PR for you this time.

**Comment by niemyjski** [comment] 2019-01-25 15:00
This was fixed in 4.3.1

**Closed by niemyjski** 2019-01-25 15:00 UTC
Labels: bug
