### ISSUE TITLE
MVC package missing 404 handling?

### ISSUE THREAD

**Issue by Kordonme** [exceptionless/Exceptionless.Net#48] opened 2015-08-17 09:22 UTC
Hi guys,

How come the MVC client doesn't contain these few lines:

https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Platforms/Web/ExceptionlessWebPlugin.cs#L44-L52

We have some applications where a developer threw a 404 like this:

    throw new HttpException(404, "<msg>");

And we expected them to show up as Broken Links, but instead they show up as Exceptions.

Is this intended behaviour?

**Comment by Kordonme** [comment] 2015-08-17 09:33
Oh, I see the plugin is being registered. However, it's not the experience we get:

https://github.com/exceptionless/Exceptionless.Net/blob/4deb3de8c09d353ce0dfd96659b00bae07e51893/Source/Platforms/Mvc/ExceptionlessModule.cs#L17

**Comment by Kordonme** [comment] 2015-08-17 13:16
Also, we are experiencing double error reporting. Both from HttpApplicationError and AndErrorsAttribute.

Line 15 and 23:

https://github.com/exceptionless/Exceptionless.Net/blob/4deb3de8c09d353ce0dfd96659b00bae07e51893/Source/Platforms/Mvc/ExceptionlessModule.cs

**Comment by niemyjski** [comment] 2015-08-17 14:55
@Kordonme so you're not seeing the same 404 experience? Is the stack trace the exact same for both of your errors?

**Comment by Kordonme** [comment] 2015-08-18 09:07
Well, it's kind of two different issues. 

The first one is HttpExceptions being thrown with 404 is being registered as exceptions (http://i.imgur.com/zIhjz4B.png). Expected behaviour is it being reported under Broken Links. Or am I missing something?

Another issue is the application reporting same error, 100% identical, two times. First with the `SendErrorsAttribute` and afterwards from `HttpApplicationError`. I found out by setting a breakpoint in `SubmittingEvent` and checked the `submission_method`.

**Comment by niemyjski** [comment] 2015-08-18 13:40
I think #1 is an issue I'm not 100% sure about the second, if you can send me a link to both of the errors I can let you know more. If the stack trace isn't 100% the same then duplicates will occur, this can happen if the stack trace is different at the two error handlers

**Comment by Kordonme** [comment] 2015-08-18 14:55
Regarding duplicate errors, you are right. But there are still being sent two errors with different submission_methods, and slightly different stack traces:

```
System.Exception: This is a test exception
at Application.Controllers.<Controller>.<Action>(<args>) at offset 24 in <file> 26:col 13
at lambda_method(System.Runtime.CompilerServices.Closure, System.Web.Mvc.ControllerBase, System.Object[]) at offset -1
at System.Web.Mvc.ActionMethodDispatcher.Execute(System.Web.Mvc.ControllerBase controller, System.Object[] parameters) at offset 0
at System.Web.Mvc.ReflectedActionDescriptor.Execute(System.Web.Mvc.ControllerContext controllerContext, System.Collections.Generic.IDictionary`2 parameters) at offset 114
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(System.Web.Mvc.ControllerContext controllerContext, System.Web.Mvc.ActionDescriptor actionDescriptor, System.Collections.Generic.IDictionary`2 parameters) at offset 0
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.b__41() at offset 0
at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass8`1.b__7(System.IAsyncResult _) at offset 0
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() at offset 41
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(System.IAsyncResult asyncResult) at offset 0
at System.Web.Mvc.Async.<>c__DisplayClass37.<>c__DisplayClass39.b__33() at offset 30
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.b__49() at offset 134
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.b__36(System.IAsyncResult asyncResult) at offset 0
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() at offset 41
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(System.IAsyncResult asyncResult) at offset 0
at System.Web.Mvc.Async.<>c__DisplayClass25.<>c__DisplayClass2a.b__20() at offset 0
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.b__22(System.IAsyncResult asyncResult) at offset 65

// the stack traces differs in this part. The lines below are in one of the stack traces.
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() at offset 41
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(System.IAsyncResult asyncResult) at offset 0
at System.Web.Mvc.Controller.<>c__DisplayClass1d.b__18(System.IAsyncResult asyncResult) at offset 0
at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(System.IAsyncResult ar) at offset 0
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() at offset 41
at System.Web.Mvc.Controller.EndExecuteCore(System.IAsyncResult asyncResult) at offset 0
at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.b__3(System.IAsyncResult ar) at offset 0
at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End() at offset 41
at System.Web.Mvc.Controller.EndExecute(System.IAsyncResult asyncResult) at offset 0*
```

**Comment by niemyjski** [comment] 2015-08-18 19:07
Yes, there is nothing we can do about this, we log the exception as part of the handler and let the rethrow happen automatically by the framework (mvc). If the inner exceptions match than we discard them, but they don't so we don't know if it's a duplicate or not. There's really no good way to solve this.

**Comment by niemyjski** [comment] 2015-08-18 19:13
Thoughts?

**Comment by niemyjski** [comment] 2015-08-21 18:15
I'm closing this as I wasn't able to reproduce this in our sample:

![image](https://cloud.githubusercontent.com/assets/1020579/9415691/a8f14838-4806-11e5-9890-b7afa9609731.png)

**Comment by niemyjski** [comment] 2015-08-21 18:27
If you can send us a repo where you are seeing this behavior, please comment with the info and we will reopen this issue.

**Comment by Kordonme** [comment] 2015-09-22 08:04
Well, this seem to be an on/off problem. Sometimes it's handled correctly and is placed under broken links, but we get a lot of data cluttering our exceptions:

http://i.imgur.com/abcuoux.png

We can't really use this view because of these incorrectly placed errors. They are sent via SendErrorsAttribute

`throw new HttpException(404, "Page not found.");`

**Comment by niemyjski** [comment] 2015-09-22 22:45
That is really odd. Is there any chance you could pull down this repo and take a look at our web sample that throws a 404 via HtpException and see what's different between the two apps. If I can reproduce it in a sample of some kind, I can fix this issue.

**Comment by Kordonme** [comment] 2015-09-23 03:50
I might have an idea where to look. I will try and get to it this weekend.

**Comment by niemyjski** [comment] 2015-10-31 15:06
@Kordonme Any luck on creating a sample?

**Comment by niemyjski** [comment] 2015-11-23 23:40
@Kordonme Any lucks tracking this down?

**Comment by yetanotherchris** [comment] 2015-12-23 16:23
We're also getting doubled-up exceptions, the problem appears to be because the HttpModule registers a global IExceptionFilter attribute:

https://github.com/exceptionless/Exceptionless.Net/blob/8385a907c3066197be1d69b39dda5c6bc780b5aa/Source/Platforms/Mvc/ExceptionlessModule.cs#L22

I try clearing it, but the module re-registers it everytime.

        public ActionResult Index()
        {
			GlobalFilters.Filters.Clear();

			throw new AccessViolationException("Foo bar");
	}

The exceptions are identical from each source.

**Comment by yetanotherchris** [comment] 2015-12-23 16:29
I'm confused how duplicate exceptions aren't always sent, when exceptions are sent to Exceptionless in the HttpApplication (https://github.com/exceptionless/Exceptionless.Net/blob/8385a907c3066197be1d69b39dda5c6bc780b5aa/Source/Platforms/Web/ExceptionlessClientExtensions.cs) and through this filter. You mentioned they are discarded, but is there any point having an IExceptionFilter if the HttpApplication catches them anyway?

**Comment by niemyjski** [comment] 2015-12-23 18:00
We hook into every error handling point that we can because over time we've found that sometimes exceptions are lost if you don't. We have a deduplicating plugin that runs on the client for every event and it checks to see if an error has already been submitted within the past 2 seconds, if it has we discard it. In this case we should do more to investigate if we wrap and rethrow the exception if it will be discarded.

**Comment by niemyjski** [comment] 2016-01-14 18:09
@yetanotherchris I've fixed the duplicate issue and that will be shipping in 3.2 soonish. I'm going to close this as I've yet been able to reproduce this issue. If you can reproduce, please reopen this issue with a sample and we'll get this fixed.

**Closed by niemyjski** 2016-01-14 18:09 UTC
Labels: bug, investigating
