### ISSUE TITLE
slowly insert after high frequency rate Client request!

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless.Net#154] opened 2017-05-22 10:24 UTC
I met a problem as below:

1.I have 100 jobs to do something and use the ExceptionlessClient.Default to insert my business logs.
2. but i found that the logs(about 500/**1 sec**) produced by the jobs were slowly inserted, the count rate in the dashboard was about 350~450/ **5 sec**
3. When I stop my jobs(no log insert), I found that the count in the dashboard was still growing（just like a background thread still working）for long time.
4.wait for some minutes，the count in the dashboard was stop(maybe the background thread works completed).

Now. 
1.Is there any mechanism in the underlying? queue or background thread?
2.How can I improve the “Real-time” rate of inserting? any config in web.config?

PS：
1. the host machine of the Exceptionless is 16 cpus and 8GB memory,and about 5%~10% cpus loaded while my business jobs running!

**Comment by ZhiqiangTao** [comment] 2017-05-22 13:16
thanks for your replay in advanced

**Comment by niemyjski** [comment] 2017-05-22 14:59
The client submits events on a background timer every 10 seconds, you could change this setting but its going to add overhead to your app and less likely to submit results in batch. Are you using the in memory storage on the client (default)? 

The items server side will be queued when received (every 10 seconds) and processed as quickly as possible). Are you using dedicated jobs? You can run multiple event post instances. Also is elasticsearch and redis on the same machine?

**Comment by ZhiqiangTao** [comment] 2017-05-22 22:19
thanks you firstly.
But I still have some problems for your reply.
1.I don't code "Client.Configuration.UseInMemoryStorage();" in my project, is it means that I don't use memory storage? If yes, what's the benefits of this feather? is the Out of Memory exception will pop up while many logs are produced by my service if I enable this feature?

2. " Are you using **dedicated jobs**? You can run multiple **event post instances**." you said, 
a.is the **" **dedicated jobs"**** means that "Running jobs out of process"? just like the link:https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting.
b.is the "You can run multiple **event post instances**" means that I should do as below steps(copy from above link), if yes, does the "**\App_Data\jobs\continuous\EventPost**" should be run as multiple instances?

   By default, all jobs run in process. If you find that your event processing is falling behind continually you can fire up and scale out multiple job instances. By running the jobs out of process you are responsible for ensuring all jobs are running or some functionality will not work.

0.Setup Redis by following the steps above. This allows exceptionless to communicate to the jobs that are running out of process.
1.Update the Web.config file and set the RunJobsInProcess AppSetting to false.
2.You'll need to update the job configuration settings. You can do this one of two ways:
3.Use environment variables to configure exceptionless. You can do this by adding a new environment variable with Exceptionless_{SETTING NAME} (Example: Exceptionless_BaseURL, Exceptionless_ElasticSearchConnectionString). We recommend this approach as it's easier and works great when deploying to azure.
4.Open the App_Data\jobs folder and configure each job's xxxx.exe.config with the configuration settings you have defined in your root web.config
5.Launch the jobs located in the App_Data\jobs folder and click the run.bat file to run the selected job. You can set these to run as a service or run manually.

3.Currently, I don't use redis.

**Comment by ZhiqiangTao** [comment] 2017-05-22 22:20
Forgive me for having so many questions. aha

**Comment by ZhiqiangTao** [comment] 2017-05-23 01:04
Maybe I get the key:
https://exceptionless.com/sending-log-messages-to-exceptionless/

**Comment by niemyjski** [comment] 2017-05-23 14:58
1. If you don't have that, that means you are using in memory storage (default) and it's what we recommend for high throughput scenarios. We should be clearing the queue frequently and that shouldn't be an issue. I'm going to open an issue to ensure we put a cap on in memory queued items. (https://github.com/exceptionless/Exceptionless.Net/issues/155)
2. Yes, that is what I was referring to, running in memory is fine. Just note you just won't be able to scale up as quickly if the instance is getting hammered with events. I'd recommend at least using redis so if your app restarts the queued items will resume across app restarts.

What we recommend for best performance is to run an elasticsearch cluster on a different box as well as redis as both of those are io an memory intensive. Then exceptionless can just be hosted in iis. However, your setup will work fine unless you find yourself with Low memory + high disk io when processing millions of events.

**Comment by edwardmeng** [comment] 2017-08-13 00:57
I think it's fixed in pr #161 due to performance issue, that we have encountered this problem too days ago.

**Comment by niemyjski** [comment] 2017-08-13 14:21
I'll get a new client release out.

**Closed** 2017-08-13 14:22 UTC

**Comment by ZhiqiangTao** [comment] 2017-11-06 07:50
@niemyjski 
1.it's mean that I can use the latest 4.0.1955 client to insert about 350~450/ 5 sec logs and without any delay？
2. I updated the exceptionless website from 4.0.1 to 4.1.0 and  4.0.1955 Nuget, I found that the logs wouldn't be inserted into the "\Exceptionless.4.1.2861\wwwroot\App_Data\storage\q", but in "D:\Exceptionless.4.1.2861\wwwroot\App_Data\storage\archive". is this by design? or bug?

thanks for you in advanced!

**Comment by niemyjski** [comment] 2017-11-06 12:26
This is by design, as we can skip a bunch of IO work if we move this to the archive folder by default. The next release will show a big perf improvement and the ones after that even more :)

**Comment by ZhiqiangTao** [comment] 2017-11-06 12:29
so cool, look forward to the next release, aha， when can I get the next release?

**Comment by niemyjski** [comment] 2017-11-06 14:56
We are note sure but we hope real soon, we are doing lots of testing as it's pretty much a rewrite in the sense (Migrated from legacy to asp.net to asp.net core)
