### ISSUE TITLE
Package installation script doesn't create configSections element

### ISSUE THREAD

**Issue by haliphax** [exceptionless/Exceptionless.Net#90] opened 2016-04-05 18:37 UTC
In Visual Studio 2013, when installing the `Exceptionless` package, the following errors occur:

````
PM> install-package Exceptionless
Attempting to resolve dependency 'Exceptionless.Portable (= 3.3.1590)'.
Installing 'Exceptionless.Portable 3.3.1590'.
Successfully installed 'Exceptionless.Portable 3.3.1590'.
Installing 'Exceptionless 3.3.1590'.
Successfully installed 'Exceptionless 3.3.1590'.
Adding 'Exceptionless.Portable 3.3.1590' to ExceptionlessTest.
Successfully added 'Exceptionless.Portable 3.3.1590' to ExceptionlessTest.
Unable to index into an object of type System.Xml.XmlChildNodes.
At C:\users\REDACTED\documents\visual studio 2013\Projects\ExceptionlessTest\packages\Exceptionless.Portable.3.3.1590\tools\exceptio
nless.psm1:46 char:178
+                     $parentNode = $configXml.SelectSingleNode("configuration").InsertBefore($configXml.CreateElement('configSecti
ons'), $configXml.SelectSingleNode("configuration").ChildNodes[ <<<< 0])
    + CategoryInfo          : InvalidOperation: (0:Int32) [], RuntimeException
    + FullyQualifiedErrorId : CannotIndex
 
You cannot call a method on a null-valued expression.
At C:\users\REDACTED\documents\visual studio 2013\Projects\ExceptionlessTest\packages\Exceptionless.Portable.3.3.1590\tools\exceptio
nless.psm1:53 char:27
+             $parentNode.AppendChild <<<< ($configSection)
    + CategoryInfo          : InvalidOperation: (AppendChild:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Adding 'Exceptionless 3.3.1590' to ExceptionlessTest.
Successfully added 'Exceptionless 3.3.1590' to ExceptionlessTest.
Unable to index into an object of type System.Xml.XmlChildNodes.
At C:\Users\REDACTED\Documents\Visual Studio 2013\Projects\ExceptionlessTest\packages\Exceptionless.3.3.1590\tools\exceptionless.psm
1:46 char:178
+                     $parentNode = $configXml.SelectSingleNode("configuration").InsertBefore($configXml.CreateElement('configSecti
ons'), $configXml.SelectSingleNode("configuration").ChildNodes[ <<<< 0])
    + CategoryInfo          : InvalidOperation: (0:Int32) [], RuntimeException
    + FullyQualifiedErrorId : CannotIndex
 
You cannot call a method on a null-valued expression.
At C:\Users\REDACTED\Documents\Visual Studio 2013\Projects\ExceptionlessTest\packages\Exceptionless.3.3.1590\tools\exceptionless.psm
1:53 char:27
+             $parentNode.AppendChild <<<< ($configSection)
    + CategoryInfo          : InvalidOperation: (AppendChild:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
````

**Comment by niemyjski** [comment] 2016-08-17 13:51
@haliphax are you still seeing this with the latest client package?

**Comment by niemyjski** [comment] 2016-08-17 14:45
I was able to reproduce and this is fixed in a nightly which will be pushed shortly. This was happening because the app.config didn't have a `<configuration>` node.

**Closed by niemyjski** 2016-08-17 14:45 UTC
Labels: bug

**Comment by haliphax** [comment] 2016-08-18 14:34
Sorry I didn't respond - been dealing with a newborn, so I haven't been regularly checking up on things. :) For the record, I had a pretty flawless install on a newer version of Windows, IIS, and .NET when we put Exceptionless into production.

**Comment by niemyjski** [comment] 2016-08-18 14:41
Thanks for the heads up and congrats on the new born! I've fixed your original issue and it's been deployed. If you have any feedback please let us know!
