### ISSUE TITLE
StackOverflowException with EventBuilder

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.Net#26] opened 2015-06-09 13:13 UTC
```
ExceptionlessClient.Default.SubmittingEvent += (sender, e) =>
                    {
                        if (e.IsUnhandledError)
                        {
                                var builder = new EventBuilder(e.Event, e.Client, , e.PluginContextData);
                                builder.AddTagsUnhandled").Submit(); // <-- Generates a StackOverFlowException when e.PluginContextData is also added to the above constructor.
                                e.Cancel = true;
                        }
                    };         
 ```

**Comment by niemyjski** [comment] 2015-06-09 14:13
This happens because your reusing the plugin context data which marks this newly submitted error as an unhandled error. If you just want to add a tag to the event, it's much more effient to just do:

```csharp
client.SubmittingEvent += (sender, e) => {
    if (e.IsUnhandledError)
        e.Event.Tags.Add("Unhandled");
};
```

**Comment by niemyjski** [comment] 2015-06-09 14:30
@ejsmith  I'm closing this issue as by design (we have a unit test for it) unless the general consensus is that we should handle this behavior differently.

**Closed by niemyjski** 2015-06-09 14:30 UTC
Labels: bug, by design
