### ISSUE TITLE
Duplicate errors with unhandled exceptions in ASP.NET MVC application

### ISSUE THREAD

**Issue by Drel** [exceptionless/Exceptionless.Net#65] opened 2015-12-23 00:34 UTC
I just switched from AppFail.Net due to extremely lengthy delays in notification, to try out Exceptionless.Net.  I was able to easily add the libraries using NuGet:

    PM> Install-Package Exceptionless.MVC -Source nuget.org
    Attempting to resolve dependency 'Exceptionless.Portable (= 3.2.1424)'.
    Installing 'Exceptionless.Portable 3.2.1424'.
    Successfully installed 'Exceptionless.Portable 3.2.1424'.
    Installing 'Exceptionless.Mvc 3.2.1424'.
    Successfully installed 'Exceptionless.Mvc 3.2.1424'.
    Adding 'Exceptionless.Portable 3.2.1424' to PTS.WebUI.
    Successfully added 'Exceptionless.Portable 3.2.1424' to PTS.WebUI.
    Adding 'Exceptionless.Mvc 3.2.1424' to PTS.WebUI.
    Successfully added 'Exceptionless.Mvc 3.2.1424' to PTS.WebUI.

However, after compiling and triggering an unhandled exception, I receive two identical errors logged in the Exceptionless dashboard (in my case, it's a System.NullReferenceException) for every exception I generate.

I have made no changes to the default configuration other than setting my Exceptionless apiKey in Web.config.  I have already removed the AppFail libraries and configuration from web.config.

**Comment by niemyjski** [comment] 2015-12-23 16:53
This sometimes happens when exceptions are bubbled up through multiple error handlers. I have a task to look into to see if we wrap these and rethrow if we can deduplicate the exceptions. Are the exception stack traces exactly the same?

**Comment by Drel** [comment] 2015-12-23 17:16
Could this be caused because I'm also using ELMAH to log errors locally?

Good question re: identical stack traces -- the first stack trace is fairly short, the second stack trace is identical to the first one for the length of the first, but then has the following appended onto it:

	at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.b__1e(System.IAsyncResult asyncResult) at offset 65
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at offset 41
	at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](System.IAsyncResult asyncResult, System.Object tag) at offset 7
	at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(System.IAsyncResult asyncResult, System.Web.Mvc.ExecuteCoreState innerState) at offset 0
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at offset 41
	at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](System.IAsyncResult asyncResult, System.Object tag) at offset 7
	at System.Web.Mvc.Async.AsyncResultWrapper.End(System.IAsyncResult asyncResult, System.Object tag) at offset 0
	at System.Web.Mvc.Controller.EndExecuteCore(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.Controller.<BeginExecute>b__15(System.IAsyncResult asyncResult, System.Web.Mvc.Controller controller) at offset 0
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at offset 41
	at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](System.IAsyncResult asyncResult, System.Object tag) at offset 7
	at System.Web.Mvc.Async.AsyncResultWrapper.End(System.IAsyncResult asyncResult, System.Object tag) at offset 0
	at System.Web.Mvc.Controller.EndExecute(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(System.IAsyncResult asyncResult, System.Web.Mvc.ProcessRequestState innerState) at offset 0
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at offset 41
	at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](System.IAsyncResult asyncResult, System.Object tag) at offset 7
	at System.Web.Mvc.Async.AsyncResultWrapper.End(System.IAsyncResult asyncResult, System.Object tag) at offset 0
	at System.Web.Mvc.MvcHandler.EndProcessRequest(System.IAsyncResult asyncResult) at offset 0
	at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(System.IAsyncResult result) at offset 0
	at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at offset 203
	at System.Web.HttpApplication.ExecuteStep(System.Web.IExecutionStep step, System.Boolean& completedSynchronously) at offset 54

**Comment by niemyjski** [comment] 2015-12-23 18:01
I think this is directly related to this: https://github.com/exceptionless/Exceptionless.Net/issues/48#issuecomment-166936929 It happens due to multiple error handlers catching the same exception but the stack trace is different so we don't discard them. I'm going to mark this as a bug and we should see if we can wrap the exception and rethrow if it's discarded.

**Comment by Drel** [comment] 2015-12-23 18:08
Sounds great, thank you!  Apologies for the duplicate bug, I looked through the issues before filing, but didn't catch the other one since it was filed under "MVC package missing 404 handling?".

**Comment by yetanotherchris** [comment] 2016-01-04 11:17
For now, I've removed this line:

- https://github.com/exceptionless/Exceptionless.Net/blob/8385a907c3066197be1d69b39dda5c6bc780b5aa/Source/Platforms/Mvc/ExceptionlessModule.cs#L22

And recreated the HttpModule in a custom HttpModule, adding the `ExceptionlessWebPlugin` source.

Would it be possible to add a configuration option to make the filter registration optional? For example:

    Exceptionless.ExceptionlessClient.Default.Configuration.RegisterExceptionlessFilter()

I realise this is a breaking change, but even the simplest MVC app is doubling exceptions right now.

**Comment by niemyjski** [comment] 2016-01-04 15:28
I'm in the process of finishing a major new feature on both client and the api. and then I'll take a look into this (if one of you could help with my suggestion of wrapping the errors before we rethrow, that would be greatly appreciated).

**Comment by niemyjski** [comment] 2016-01-04 15:29
I do think that we might be able to get rid of one of the error handlers. But I'd want to be 100% sure that the one we do remove is being covered by the other integration point.

**Comment by yetanotherchris** [comment] 2016-01-05 21:14
I'm happy to help out, what is the reasoning behind not sending too many of the same errors at once? In terms of the error attribute, I've only used it on its own for MVC related errors (or OnException in ControllerBase) to redirect to a view rather than to log, when you want ever single error including 404s from IIS the HttpApplication one seems better.

**Comment by niemyjski** [comment] 2016-01-06 18:01
Yeah, we just want to cut down on the number of exceptions being logged if they are the same exception. I think we need to look into wrapping the exception before rethrowing it in the mvc client. Can you look into this?

**Comment by yetanotherchris** [comment] 2016-01-08 10:52
An would an MD5 of the exception.ToString() be enough?

**Comment by niemyjski** [comment] 2016-01-08 13:17
No, we are already doing it intelligently based on the hash, the problem is the stack traces are being changed because it's being rethrown so we need to wrap it in a new exception and rethrow it so we de duplicate it. I'm finishing up some this major feature hopefully today and I'll take a closer look at this.

**Comment by niemyjski** [comment] 2016-01-14 18:07
After doing some researching I think we are fine with ignoring `HttpApplication.OnError` handler and just using the global filter. I did some testing and it seems that we are picking up all exceptions. I'm leaving the existing extension methods for wiring up to `HttpApplication.OnError` incase anyone wants them. This is committed in a branch and will be fixed in 3.2 which will be deploying soonish.

**Closed by niemyjski** 2016-01-14 18:07 UTC
Labels: bug, investigating

**Comment by niemyjski** [comment] 2016-01-18 22:47
These changes have been pushed
