### ISSUE TITLE
How to do logging in Application_Start?

### ISSUE THREAD

**Issue by skoub** [exceptionless/Exceptionless.Net#40] opened 2015-07-16 13:48 UTC
I would like to log when my application start and when the application end. My code look like this but it doesn't log anything but it work when i log something in an ActionResult.

```
protected void Application_Start()
{
    AreaRegistration.RegisterAllAreas();
    FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
    RouteConfig.RegisterRoutes(RouteTable.Routes);
    BundleConfig.RegisterBundles(BundleTable.Bundles);

    ExceptionlessClient.Default.SubmitLog("Application started");
}
```

And any idea why the logging doesn't work there?

**Comment by niemyjski** [comment] 2015-07-16 15:02
It could be caused by the fact that the config section hasn't been read yet (it's set when the http handler executes which could be before or after this code runs??). What is `ExceptionlessClient.Default.Configuration` look like? Is the api key set? Are you using the mvc package?

**Comment by skoub** [comment] 2015-07-16 15:38
The apiKey is not set when i'm in the Application_Start and yes i'm using the mvc package. Like you've said, the client is not ready yet when i'm in the application_start.

I tried to start the clien myself and it work but i'm not sure if it's a good idea to do it that way:

```
protected void Application_Start()
{
    ExceptionlessClient.Default.Startup();

    AreaRegistration.RegisterAllAreas();
    FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
    RouteConfig.RegisterRoutes(RouteTable.Routes);
    BundleConfig.RegisterBundles(BundleTable.Bundles);

    ExceptionlessClient.Default.SubmitLog("Application started");
}
```

**Comment by niemyjski** [comment] 2015-07-16 15:44
I don't see it hurting anything, but I usually advise against setting something that is automatically handled for you. But in this case without calling it you wouldn't get the log message right there (so it's up to you).

In our application we also write a message after everything's been bootstrapped (di has been configured), but we write the log message out via nlog and have a nlog exceptionless target.

**Comment by niemyjski** [comment] 2015-07-16 15:45
@ejsmith @skoub What do you think? This should be the only method in an mvc app where exceptionless may or may not be configured.

**Comment by ejsmith** [comment] 2015-07-16 18:23
I don't think there is anything wrong with calling the startup method. I know we have tested it in the past to make sure calling it multiple times doesn't hurt anything.

**Comment by niemyjski** [comment] 2015-07-16 18:42
yes, I'm going to close this as you can call `ExceptionlessClient.Default.Startup()` if you wish to log inside of this method.

**Closed by niemyjski** 2015-07-16 18:42 UTC
Labels: question

**Comment by skoub** [comment] 2015-07-17 15:24
@niemyjski why if you log with nlog in the Application_Start, the log will exist in Exceptionless but not if i use Exceptionless client?

anyway, with NLog, it work great! thank you!

and do you also log when the application shutdown? if yes, i would be interested to know how you do that.

**Comment by niemyjski** [comment] 2015-07-17 15:35
Because the nlog client will use it's own key and in memory queue if configured that way. We personally don't do that as I don't really think it adds too much value. But you could just wireup to application end I think in mvc.

**Comment by niemyjski** [comment] 2015-07-17 15:36
Does this make sense?

**Comment by skoub** [comment] 2015-07-17 17:12
i will try that. Thank you for your help!

**Comment by niemyjski** [comment] 2015-07-20 17:13
No problem!
