### ISSUE TITLE
Heads up to (aspnet) core error tracking

### ISSUE THREAD

**Issue by MihaMarkic** [exceptionless/Exceptionless.Net#144] opened 2017-03-19 10:34 UTC
Found out that exceptionless in my aspnet core (.net target) doesn't work at all.
After enabling error logging I saw this message:

> DefaultEventQueue: An error occurred while submitting events: Inheritance security rules violated by type: 'System.Net.Http.WebRequestHandler'. Derived types must either match the security accessibility of the base type or be less accessible.
> DefaultEventQueue: Suspending processing for: 00:05:00.

I think this is the same error as discussed in this (long) [thread](https://github.com/dotnet/corefx/issues/11100).

Now, for me it started working when I manually referenced System.Net.Http 4.3.**1** nuget package (which in turn updated the implicitly referenced 4.3.0).
HTH

**Comment by MihaMarkic** [comment] 2017-03-19 10:40
One way to solve it could be that System.Net.Http 4.3.1 is referenced by the library?

**Comment by niemyjski** [comment] 2017-03-20 21:20
Are you running on the full framework? Thanks for reporting this, this is a duplicate of (#142) which I'm actively looking into. So did you update system.net.http In your app?

**Closed by niemyjski** 2017-03-20 21:20 UTC

**Comment by MihaMarkic** [comment] 2017-03-20 21:22
yes and yes
