### ISSUE TITLE
Why can't Info level logs be uploaded to Exceptionless

### ISSUE THREAD

**Issue by lwyjan** [exceptionless/Exceptionless.Net#264] opened 2021-12-09 09:25 UTC
The Exceptionless version I am using is v2.7.1. When I use Exceptionless.NLog of version 4.6.2, Info level logs cannot be uploaded to Exceptionless, but Warn and Error logs can be uploaded.

![image](https://user-images.githubusercontent.com/11329837/145369236-d0bc0041-3011-4b3a-a8b1-570f5b6c12a3.png)
![image](https://user-images.githubusercontent.com/11329837/145369300-cb72a576-e586-4489-a515-23c7983dde4f.png)
![image](https://user-images.githubusercontent.com/11329837/145369404-e68eff96-6c11-4620-977c-32c2aee33ba6.png)

**Comment by niemyjski** [comment] 2021-12-09 15:28
This is due to the DefaultMinLogLevel that's defined on the client. Please see the readme for more information: https://github.com/exceptionless/Exceptionless.Net/blob/118b006c1c66c7fcc2c668f91af5a27cad8bd2ab/src/Platforms/Exceptionless.NLog/readme.txt#L30 Please note we recommend using the default client instance (remove the target api key to use the default instance) so you can configure this setting. It's not currently possible to set this setting via the nlog target.

**Comment by lwyjan** [comment] 2021-12-10 06:26
> This is due to the DefaultMinLogLevel that's defined on the client. Please see the readme for more information:
> 
> https://github.com/exceptionless/Exceptionless.Net/blob/118b006c1c66c7fcc2c668f91af5a27cad8bd2ab/src/Platforms/Exceptionless.NLog/readme.txt#L30
> 
> Please note we recommend using the default client instance (remove the target api key to use the default instance) so you can configure this setting. It's not currently possible to set this setting via the nlog target.

Using the latest version of https://be.exceptionless.io/, it is possible to upload Info level logs normally. At present, I am using a relatively low version of Exceptionless, which seems to be a version incompatibility issue.
Find a similar issue here https://github.com/exceptionless/Exceptionless.Net/issues/260

**Comment by niemyjski** [comment] 2021-12-10 13:30
Yes, this seems to be the case and a duplicate, I'd recommend upgrading as well as setting that setting until server side settings can be retrieved.

**Comment by niemyjski** [comment] 2021-12-16 15:17
Did upgrading help? I'm going to close this as I feel this is a duplicate of #260

**Closed by niemyjski** 2021-12-16 15:17 UTC
